---
language: python
python:
  - "2.7"
  - "3.6"
env:
  - ROLE=dns-server
  - ROLE=l4-lb
  - ROLE=l7-lb
  - ROLE=router
  - ROLE=webserver
services:
  - docker
install:
  - pip install -r requirements.txt
script:
  - molecule --version
  - ansible --version
  - cd roles/$ROLE
  - molecule test
